import java.io.BufferedWriter;

import java.io.FileInputStream;

import java.io.FileWriter;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.Hashtable;
import java.util.Properties;

public class RetriveListMenu {

	/**
	 * @param argv
	 */
	public static void main(String[] argv) {
		Properties prop = new Properties();

		Connection connection = null;
		PreparedStatement stmt = null;

		BufferedWriter output;
		try {

			Class.forName("oracle.jdbc.driver.OracleDriver");
			prop.load(new FileInputStream("data.properties"));
			// propMenu.load(new FileInputStream("RetriveListMenu.properties"));
			String url = prop.getProperty("url");
			String userName = prop.getProperty("username");
			String password = prop.getProperty("password");
			String groupName = prop.getProperty("GROUP_NAME");
			String OutPutPath = prop.getProperty("OutPutPath");
			connection = DriverManager.getConnection(url, userName, password);

			Hashtable<Integer, String> hmap = new Hashtable<Integer, String>();

			hmap.put(1, "Review Held Transactions");
			hmap.put(2, "Investigation Queue");
			hmap.put(3, "Manual Review -All");
			hmap.put(4, "Manual Review - Not Reviewed");
			hmap.put(5, "Manual Review- Reviewed Once");
			hmap.put(6, "Statistics");
			hmap.put(7, "Risk Entity");
			hmap.put(8, "Records");
			hmap.put(9, "Advanced Risk Entity Search");
			hmap.put(10, "Associated Items");
			hmap.put(11, "Criteria Sets");
			hmap.put(12, "Dictionary Search");
			hmap.put(13, "Export");
			hmap.put(14, "Good Guys");
			hmap.put(15, "Risk Entity Details");
			hmap.put(16, "Programs");
			hmap.put(17, "Import Lists");
			hmap.put(18, "Import HM Treasury List");
			hmap.put(19, "Import EU List");
			hmap.put(20, "Import EU Excel");
			hmap.put(21, "ISO Code");
			hmap.put(22, "Import Multi-List");
			hmap.put(23, "Import NYCH");
			hmap.put(24, "Import OFAC");
			hmap.put(25, "Import World-Check List");
			hmap.put(26, "Verify Lists");
			hmap.put(27, "Verify HM Treasury");
			hmap.put(28, "Verify EU");
			hmap.put(29, "Verify NYCH");
			hmap.put(30, "Verify EU Excel");
			hmap.put(31, "General");
			hmap.put(32, "City");
			hmap.put(33, "Clear Marked Records");
			hmap.put(34, "Country");
			hmap.put(35, "Mark Records");
			hmap.put(36, "Initials Generation");
			hmap.put(37, "Acronym Generation");
			hmap.put(38, "Additional Info Captions");
			hmap.put(39, "Risk Entity Approvals");
			hmap.put(40, "Approve Associated Items");
			hmap.put(41, "Approve City");
			hmap.put(42, "Approve Country");
			hmap.put(43, "Approve Criteria Sets");
			hmap.put(44, "Approve Good Guys");
			hmap.put(45, "Approve ISO Codes");
			hmap.put(46, "Approve Programs");
			hmap.put(47, "Approve Delete List");
			hmap.put(48, "Approve Risk Entity Details");
			hmap.put(49, "Approve Initial Generation");
			hmap.put(50, "Approve Acronym Generation");
			hmap.put(51, "Approve Additional Info");
			hmap.put(52, "Users");
			hmap.put(53, "Expire User Passwords");
			hmap.put(54, "Group Privileges");
			hmap.put(55, "Location ID");
			hmap.put(56, "Restricted Passwords");
			hmap.put(57, "Security Policy");
			hmap.put(58, "User Privileges");
			hmap.put(59, "User Approvals");
			hmap.put(60, "Approve Expire User Passwords");
			hmap.put(61, "Approve Group Privileges");
			hmap.put(62, "Approve Location ID");
			hmap.put(63, "Approve Restricted Passwords");
			hmap.put(64, "Approve Security Policy");
			hmap.put(65, "Approve User Privileges");
			hmap.put(66, "Scanning");
			hmap.put(67, "Configure Locations");
			hmap.put(68, "Amount Filter");
			hmap.put(69, "Conditional Filter");
			hmap.put(70, "User - Location Privileges");
			hmap.put(71, "Mapped Lists");
			hmap.put(72, "Settings");
			hmap.put(73, "Alpriv Settings");
			hmap.put(74, "Special Characters");
			hmap.put(75, "Scanning Approvals");
			hmap.put(76, "Approve Location Configurations");
			hmap.put(77, "Approve Amount Filter");
			hmap.put(78, "Approve Conditional Filters");
			hmap.put(79, "Approve User - Location Privileges");
			hmap.put(80, "Approve Mapped Lists");
			hmap.put(81, "Approve Settings");
			hmap.put(82, "Approve Alpriv Settings");
			hmap.put(83, "Approve Special Characters");
			hmap.put(84, "Lookup");
			hmap.put(85, "Scan Text");
			hmap.put(86, "System");
			hmap.put(87, "EOD");
			hmap.put(88, "POD");
			hmap.put(89, "Purge Audit Data");
			hmap.put(90, "Rejections");
			hmap.put(91, "Shutdown");
			hmap.put(92, "Status");
			hmap.put(93, "E-mail Notification");
			hmap.put(94, "Delta Scanning");
			hmap.put(95, "System Approvals");
			hmap.put(96, "Approve Purge Audit Data");
			hmap.put(97, "Approve E-mail Notification");
			hmap.put(98, "Approve Delta Scanning");
			hmap.put(99, "Reports");
			hmap.put(100, "Risk Entity Report");
			hmap.put(101, "Associated Items Report");
			hmap.put(102, "Criteria Sets Report");
			hmap.put(103, "Dictionary Report");
			hmap.put(104, "Good Guys Report");
			hmap.put(105, "Programs Report");
			hmap.put(106, "Scanning Report");
			hmap.put(107, "Amount Filters Report");
			hmap.put(108, "Conditional Filter Report");
			hmap.put(109, "Lookup Scan Report");
			hmap.put(110, "Mapped Lists Report");
			hmap.put(111, "Special Characters Report");
			hmap.put(112, "User - Location Report");
			hmap.put(113, "Settings Report");
			hmap.put(114, "Transactions Report");
			hmap.put(115, "Transaction Exception Report");
			hmap.put(116, "Transaction Request Report");
			hmap.put(117, "Transaction Recovery Report");
			hmap.put(118, "Unresolved Transactions Report");
			hmap.put(119, "Volume Statistics Report");
			hmap.put(120, "Hit Summary Report");
			hmap.put(121, "Users Report");
			hmap.put(122, "User Activity Report");
			hmap.put(123, "User Activity Summary Report");
			hmap.put(124, "User Maintenance Report");
			hmap.put(125, "User Privileges Report");
			hmap.put(126, "User Security Report");
			hmap.put(127, "Blocked Users Report");
			hmap.put(128, "General Report");
			hmap.put(129, "Activity Log Report");
			hmap.put(130, "Audit Report");
			hmap.put(131, "Add Risk Entity Details");
			hmap.put(132, "Delete Risk Entity Details");
			hmap.put(133, "Modify Risk Entity Details");
			hmap.put(134, "Add Group Privileges");
			hmap.put(135, "Delete Group Privileges");
			hmap.put(136, "Modify Group Privileges");
			hmap.put(137, "Add User Privileges");
			hmap.put(138, "Delete User Privileges");
			hmap.put(139, "Modify User Privileges");
			hmap.put(140, "Add Good Guy");
			hmap.put(141, "Delete Good Guy");
			hmap.put(142, "Modify Good Guy");
			hmap.put(146, "Mantas");
			hmap.put(147, "Maintain");
			hmap.put(148, "Trusted and Exempted List");
			hmap.put(149, "Watch Lists Parameters");
			hmap.put(150, "Mantas Import");
			hmap.put(151, "Import Trusted and Exempted List");
			hmap.put(152, "WatchList Export");
			hmap.put(153, "Export WatchList");
			hmap.put(154, "Approvals");
			hmap.put(155, "Approve Watchlist Parameters");
			hmap.put(156, "Approve Exempted-Trusted List");
			hmap.put(143, "Scan Mode");
			hmap.put(144, "Approve Scan Mode");
			hmap.put(145, "Verify OFAC List");
			hmap.put(157, "Session Admin");
			hmap.put(158, "City/Country");
			hmap.put(159, "Delete List");
			hmap.put(160, "Risk Entity Changes");
			hmap.put(162, "Maintain Good Guys");
			hmap.put(163, "Bulk Addition of Proposed Good Guys");
			hmap.put(164, "Good Guys Statistics and Deletion");
			hmap.put(165, "Import Good Guys");
			hmap.put(166, "Export Good Guys");
			hmap.put(167, "Proposed Good Guys Report");
			hmap.put(168, "Good Guys Statistics Report");
			hmap.put(169, "Good Guy Same As RE / Asso Item Report");
			hmap.put(170, "Good Guy CASS Export");
			hmap.put(171, "Import Factiva List");
			hmap.put(172, "System Maintenance");
			hmap.put(173, "EOD");
			hmap.put(174, "POD");
			hmap.put(175, "View EOD/POD Reports");
			hmap.put(176, "Status");
			hmap.put(177, "Shutdown");
			hmap.put(178, "Global Settings");
			hmap.put(179, "Location based Pass Threshold Settings");
			hmap.put(180, "Field Based PGG");
			hmap.put(181, "Approve Field Based PGG");
			hmap.put(182, "Processed Transactions View");
			hmap.put(183, "Field Based PGG Rule Report");
			hmap.put(184, "Import World-Check List Changes");
			hmap.put(185, "Batch Settings");
			hmap.put(186, "Batch Alpriv Settings");
			hmap.put(187, "Batch Manual Review");
			hmap.put(188, "Batch Statistics");
			hmap.put(189, "Batch Transaction Request Report");
			hmap.put(190, "Batch Settings Report");
			hmap.put(191, "Approve Batch Settings");
			hmap.put(192, "Approve Batch Alpriv Settings");
			hmap.put(193, "Global Batch Settings");
			hmap.put(194, "Location based Batch Pass Threshold Settings");
			hmap.put(195, "Field Based Scanning");
			hmap.put(196, "Approve Field Based Scanning");
			hmap.put(197, "Dictionary Reconciliation Report");
			hmap.put(198, "List Automation");
			hmap.put(199, "Approve List Automation");
			hmap.put(200, "CNS Generation");
			hmap.put(201, "Approve CNS Generation");
			hmap.put(202, "Load Dictionary Message");
			hmap.put(203, "Field Based Scanning Report");
			hmap.put(204, "Import Sanctions Alert List");
			hmap.put(205, "Import FBS Rules");
			hmap.put(206, "Export FBS Rules");
			hmap.put(207, "Email Notification-List Download");
			hmap.put(208, "Import Associated Items");
			hmap.put(209, "Export Associated Items");
			hmap.put(210, "Good Guy Administration");
			hmap.put(211, "Approve Good Guy Administration");
			hmap.put(212, "Good Guy Administration Report");
			hmap.put(213, "Manual Review-Pass");
			hmap.put(214, "Manual Review-Fail");
			hmap.put(215, "Manual Review-Bypass");
			hmap.put(216, "Manual Review-Investigate");
			hmap.put(217, "List of Matches-Pass");
			hmap.put(218, "List of Matches-Fail");
			hmap.put(232, "RT Pending Transactions");
			hmap.put(233, "Predefined Review Comments");
			hmap.put(234, "Approve Predefined Review Comments");
			hmap.put(235, "List of Matches-Investigate");
			hmap.put(236, "List of Matches-Bypass");
			hmap.put(237, "Group Location ID");
			hmap.put(238, "Approve Group Location ID");
			hmap.put(239, "Dictionary Audit Trail Report");
			hmap.put(240, "Long Word Scanning Generation");
			hmap.put(241, "Approve Long Word Scanning Generation");
			hmap.put(242, "Good Guy Same As Risk Entity");
			hmap.put(243, "Load Good Guys");
			hmap.put(244, "Investigation Queue-Pass");
			hmap.put(245, "Investigation Queue-Fail");
			hmap.put(246, "Investigation Queue-Bypass");
			hmap.put(247, "Investigation List of Matches-Pass");
			hmap.put(248, "Investigation List of Matches-Fail");
			hmap.put(249, "Investigation List of Matches-Bypass");
			hmap.put(251, "Change Business Mode");
			hmap.put(252, "Value-Added Services");
			hmap.put(253, "Search TRN Details");
			hmap.put(254, "Status and Statistics");
			hmap.put(255, "Business Mode-Normal");
			hmap.put(256, "Business Mode-Global Bypass");
			hmap.put(257, "Business Mode-Bypass Existing");
			hmap.put(258, "Business Mode-Bypass Recovery");
			hmap.put(259, "Business Mode-Recovery Normal");
			hmap.put(260, "Business Mode-Reload");
			hmap.put(261, "Business Mode-Resync");
			hmap.put(262, "Value-Added Services-Clear/Resubmit Payment");
			hmap.put(263, "Value-Added Services-Stop Swift Plug-in");
			hmap.put(264, "Value-Added Services-Release Msg Pair");
			hmap.put(265, "Value-Added Services-Purge SAI");
			hmap.put(266, "CNS Freeform");
			hmap.put(267, "CNS For FBS");
			hmap.put(268, "Approve CNS Freeform");
			hmap.put(269, "CNS-Freeform Report");
			hmap.put(270, "Import CNS-Freeform Rules");
			hmap.put(271, "Export CNS-Freeform Rules");
			hmap.put(272, "Import Generic XML List");
			hmap.put(600, "Replace Accented Characters");
			hmap.put(601, "Approve Replace Accented Characters");
			hmap.put(602, "Replace Accented Characters Report");
			hmap.put(603, "Replace Accented Characters Dict Report");
			hmap.put(604, "Import World Check List-Premium");
			hmap.put(605, "Import World Check List-Premium Changes");
			hmap.put(609, "Message Prioritization");
			hmap.put(610, "Message Boost Priority");
			hmap.put(611, "Approve Message Prioritization");
			hmap.put(612, "Approve Message Boost Priority");
			hmap.put(606, "Conditional Alpriv Settings");
			hmap.put(607, "Import Conditional Alpriv Settings");
			hmap.put(608, "Approve Conditional Alpriv Settings");
			hmap.put(613, "Export Conditional Alpriv Settings");
			hmap.put(620, "Resubmitted Transaction Rules");
			hmap.put(621, "Resubmitted Transaction Institutions");
			hmap.put(622, "Import Resubmitted Transaction Rules");
			hmap.put(623, "Import Resubmitted Transaction Institutions");
			hmap.put(624, "Approve Resubmitted Transaction Rules");
			hmap.put(625, "Approve Resubmitted Transaction Institutions");
			hmap.put(626, "Export Resubmitted Transaction Rules");
			hmap.put(627, "Export Resubmitted Transaction Institutions");
			hmap.put(628, "Res-Investigation Queue");
			hmap.put(629, "Res-Investigation Queue-Pass");
			hmap.put(630, "Res-Investigation Queue-Fail");
			hmap.put(631, "Res-Investigation Queue-Bypass");
			hmap.put(632, "Res-Investigation List of Matches-Pass");
			hmap.put(633, "Res-Investigation List of Matches-Fail");
			hmap.put(634, "Res-Investigation List of Matches-Bypass");
			hmap.put(701, "Rule Based Scanning");
			hmap.put(702, "Import Rule Based Scanning");
			hmap.put(703, "Import Field Tags");
			hmap.put(704, "Approve Rule Based Scanning");
			hmap.put(705, "Rule Based Scanning Settings Report");
			hmap.put(706, "Rule Usage Summary Report");
			hmap.put(707, "Rule Exception Report");
			hmap.put(708, "Export Rule Based Scanning");
			hmap.put(709, "Export Field Tags");
			hmap.put(710, "Watch List Integrity Config");
			hmap.put(711, "Approve Watch List Integrity Config");
			hmap.put(712, "WatchList Integrity Config Report");
			hmap.put(713, "Verify Multi List");
			hmap.put(714, "Verify Generic XML List");
			hmap.put(715, "Verify World Check List-Premium");
			hmap.put(716, "Verify Dj Lists-DJ_SANCTIONS ALERT");
			hmap.put(717, "Verify World Check List-Standard");
			hmap.put(718, "Verify DJ List-DJ_FACTIVA");
			hmap.put(719, "Verify World Check List Changes");
			hmap.put(720, "Verify World Check List");
			hmap.put(721, "Case Management Tracker");
			hmap.put(722, "Email Notification-Case Management");
			hmap.put(726, "End User Priority Rules");
			hmap.put(727, "Import End User Priority Rules");
			hmap.put(728, "Manual Review Notifications");
			hmap.put(729, "Import Manual Review Notifications");
			hmap.put(730, "Manual Review Search Filters");
			hmap.put(731, "Import Manual Review Search Filters");
			hmap.put(732, "Approve End User Priority Rules");
			hmap.put(733, "Approve Manual Review Notifications");
			hmap.put(734, "Approve Manual Review Search Filters");
			hmap.put(735, "System Report");
			hmap.put(736, "End User Priority Rules Report");
			hmap.put(737, "Manual Review Notifications Report");
			hmap.put(738, "Advance Search Filters Report");
			hmap.put(739, "Export End User Priority Rules");
			hmap.put(740, "Export Manual Review Notifications");
			hmap.put(741, "Export Manual Review Search Filters");
			hmap.put(742, "Sandbox");
			hmap.put(743, "Sync Sandbox");
			hmap.put(744, "Maintain Snapshot");
			hmap.put(745, "Approve Sync Sandbox");
			hmap.put(746, "Approve Maintain Sandbox");
			hmap.put(747, "Message Queue Statistics");
			hmap.put(753, "File Interface");
			hmap.put(754, "File Upload");
			hmap.put(75333, "File Interface Results Report");
			hmap.put(756, "Sandbox Reports");
			hmap.put(757, "Hit Summary Difference Report");
			hmap.put(758, "Transactions Hit Type Difference Report");
			hmap.put(759, "Settings Difference Report");
			hmap.put(760, "Transactions Hit Ratio Difference Report");
			hmap.put(761, "Scan Differences Report");
			hmap.put(762, "Risk Entity Type Analysis Report");
			hmap.put(763, "Risk Entity Length Analysis Report");
			hmap.put(764, "Match Percentage Range Analysis Report");
			hmap.put(765, "Top Risk Entity Hits Report");
			hmap.put(766, "Customized Transaction Request Report");
			hmap.put(767, "Scanning Performance Report");
			hmap.put(768, "Enhanced Transaction Request Report Based On Hits");
			hmap.put(748, "Message Pairing Rules");
			hmap.put(749, "Message Pairing Rules");
			hmap.put(750, "Approve Message Pairing Rules");
			hmap.put(751, "Manual Pairing Transactions");
			hmap.put(752, "Approve Manual Pairing Transactions");
			hmap.put(755, "Parked Transactions Report");
			hmap.put(769, "MX-XML Header Configuration");
			hmap.put(770, "Approve MX-XML Header Configuration");
			hmap.put(771, "Purge Case Management Tracker");
			hmap.put(772, "Approve Purge Case Management Tracker");

			ArrayList<String> arrlist = new ArrayList<String>();
			stmt = connection.prepareStatement(
					"SELECT A.MENU_ID FROM HS_PRIV_MASTER A,HS_MENUS_ASSIGNED_GRP B WHERE TRIM(UPPER(B.GRP_NAME))= ? AND A.MENU_ID=B.MENU_ID ORDER BY A.MENU_NAME");
			stmt.setString(1, groupName);

			ResultSet rs = stmt.executeQuery();
			while (rs.next()) {
				int MENU_ID = rs.getInt(1);
				// System.out.println(MENU_ID);
				if (hmap.containsKey(MENU_ID)) {
					System.out.println(hmap.get(MENU_ID));
					arrlist.add(hmap.get(MENU_ID));
				}
			}
			Collections.sort(arrlist);
			//String timeStamp = new SimpleDateFormat("yyyy:MM:dd-HH:mm:ss").format(new Date());
			System.out.println("Below Asiigned Prviledges for the Group ---------- >" + groupName);
			output = new BufferedWriter(new FileWriter(OutPutPath + groupName+".txt", false));

			for (int i = 0; i < arrlist.size(); i++) {
				System.out.println(arrlist.get(i));

				output.write(arrlist.get(i));

				output.newLine();
			}

			output.close();

		} catch (SQLException e) {
			e.printStackTrace();
		}

		catch (Exception e) {

			e.printStackTrace();
		}

	}

}
